from http import HTTPStatus
from typing import Any, cast
from urllib.parse import quote

import httpx

from ...client import AuthenticatedClient, Client
from ...types import Response, UNSET
from ... import errors

from ...models.error import Error
from ...models.get_session_frametimes_format import GetSessionFrametimesFormat
from ...models.get_session_frametimes_response_200 import GetSessionFrametimesResponse200
from ...types import UNSET, Unset
from typing import cast



def _get_kwargs(
    session_id: str,
    *,
    format_: GetSessionFrametimesFormat | Unset = UNSET,

) -> dict[str, Any]:
    

    

    params: dict[str, Any] = {}

    json_format_: str | Unset = UNSET
    if not isinstance(format_, Unset):
        json_format_ = format_.value

    params["format"] = json_format_


    params = {k: v for k, v in params.items() if v is not UNSET and v is not None}


    _kwargs: dict[str, Any] = {
        "method": "get",
        "url": "/v2/sessions/{session_id}/frametimes".format(session_id=quote(str(session_id), safe=""),),
        "params": params,
    }


    return _kwargs



def _parse_response(*, client: AuthenticatedClient | Client, response: httpx.Response) -> Error | GetSessionFrametimesResponse200 | None:
    if response.status_code == 200:
        response_200 = GetSessionFrametimesResponse200.from_dict(response.json())



        return response_200

    if response.status_code == 401:
        response_401 = Error.from_dict(response.json())



        return response_401

    if response.status_code == 404:
        response_404 = Error.from_dict(response.json())



        return response_404

    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(*, client: AuthenticatedClient | Client, response: httpx.Response) -> Response[Error | GetSessionFrametimesResponse200]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    session_id: str,
    *,
    client: AuthenticatedClient | Client,
    format_: GetSessionFrametimesFormat | Unset = UNSET,

) -> Response[Error | GetSessionFrametimesResponse200]:
    """ Raw per-frame frame-time samples (JSON or CSV)

     Returns the session's per-frame frame-time data.

    **Format toggle via `?format=csv`.** Default is JSON
    (returned by `sessionService.getSessionFrametimes`). When
    the query string contains `format=csv`, the response is a
    CSV attachment generated by
    `sessionService.getSessionFrametimesCsv`. Any other value
    of `format` (including absence) falls through to JSON.

    **Distinct from `GET /v2/sessions/{sessionId}/metrics/frametimes`.**
    That route returns the *aggregated* frame-time histogram
    derived from the metric-samples pipeline; this one returns
    the raw per-frame data straight from the session service.

    Requires the `sessions.get` permission and respects the
    caller's data scope (404 on mismatch).

    Args:
        session_id (str):
        format_ (GetSessionFrametimesFormat | Unset):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Error | GetSessionFrametimesResponse200]
     """


    kwargs = _get_kwargs(
        session_id=session_id,
format_=format_,

    )

    response = client.get_httpx_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)

def sync(
    session_id: str,
    *,
    client: AuthenticatedClient | Client,
    format_: GetSessionFrametimesFormat | Unset = UNSET,

) -> Error | GetSessionFrametimesResponse200 | None:
    """ Raw per-frame frame-time samples (JSON or CSV)

     Returns the session's per-frame frame-time data.

    **Format toggle via `?format=csv`.** Default is JSON
    (returned by `sessionService.getSessionFrametimes`). When
    the query string contains `format=csv`, the response is a
    CSV attachment generated by
    `sessionService.getSessionFrametimesCsv`. Any other value
    of `format` (including absence) falls through to JSON.

    **Distinct from `GET /v2/sessions/{sessionId}/metrics/frametimes`.**
    That route returns the *aggregated* frame-time histogram
    derived from the metric-samples pipeline; this one returns
    the raw per-frame data straight from the session service.

    Requires the `sessions.get` permission and respects the
    caller's data scope (404 on mismatch).

    Args:
        session_id (str):
        format_ (GetSessionFrametimesFormat | Unset):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Error | GetSessionFrametimesResponse200
     """


    return sync_detailed(
        session_id=session_id,
client=client,
format_=format_,

    ).parsed

async def asyncio_detailed(
    session_id: str,
    *,
    client: AuthenticatedClient | Client,
    format_: GetSessionFrametimesFormat | Unset = UNSET,

) -> Response[Error | GetSessionFrametimesResponse200]:
    """ Raw per-frame frame-time samples (JSON or CSV)

     Returns the session's per-frame frame-time data.

    **Format toggle via `?format=csv`.** Default is JSON
    (returned by `sessionService.getSessionFrametimes`). When
    the query string contains `format=csv`, the response is a
    CSV attachment generated by
    `sessionService.getSessionFrametimesCsv`. Any other value
    of `format` (including absence) falls through to JSON.

    **Distinct from `GET /v2/sessions/{sessionId}/metrics/frametimes`.**
    That route returns the *aggregated* frame-time histogram
    derived from the metric-samples pipeline; this one returns
    the raw per-frame data straight from the session service.

    Requires the `sessions.get` permission and respects the
    caller's data scope (404 on mismatch).

    Args:
        session_id (str):
        format_ (GetSessionFrametimesFormat | Unset):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Error | GetSessionFrametimesResponse200]
     """


    kwargs = _get_kwargs(
        session_id=session_id,
format_=format_,

    )

    response = await client.get_async_httpx_client().request(
        **kwargs
    )

    return _build_response(client=client, response=response)

async def asyncio(
    session_id: str,
    *,
    client: AuthenticatedClient | Client,
    format_: GetSessionFrametimesFormat | Unset = UNSET,

) -> Error | GetSessionFrametimesResponse200 | None:
    """ Raw per-frame frame-time samples (JSON or CSV)

     Returns the session's per-frame frame-time data.

    **Format toggle via `?format=csv`.** Default is JSON
    (returned by `sessionService.getSessionFrametimes`). When
    the query string contains `format=csv`, the response is a
    CSV attachment generated by
    `sessionService.getSessionFrametimesCsv`. Any other value
    of `format` (including absence) falls through to JSON.

    **Distinct from `GET /v2/sessions/{sessionId}/metrics/frametimes`.**
    That route returns the *aggregated* frame-time histogram
    derived from the metric-samples pipeline; this one returns
    the raw per-frame data straight from the session service.

    Requires the `sessions.get` permission and respects the
    caller's data scope (404 on mismatch).

    Args:
        session_id (str):
        format_ (GetSessionFrametimesFormat | Unset):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Error | GetSessionFrametimesResponse200
     """


    return (await asyncio_detailed(
        session_id=session_id,
client=client,
format_=format_,

    )).parsed
